export { default as Alert } from './components/alert/alert'
export { default as Button } from './components/button/button'
export { default as Loading } from './components/loading/index'
export { default as Card } from './components/card/index'
export { default as Switch } from './components/switch/switch'
